export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';

export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const CART_ITEM_ADD = 'CART_ITEM_ADD';

export const CART_ITEM_QUANTITY = 'CART_ITEM_QUANTITY';

export const CART_ITEM_DELETE = 'CART_ITEM_DELETE';

export const CART_ITEM_QUANTITY_DELETE = 'CART_ITEM_QUANTITY_DELETE';

export const CART_TOTAL_ADD ='CART_TOTAL_ADD';

export const CART_LOCAL_STORAGE = 'CART_LOCAL_STORAGE';

export const ADD_COUNT = 'ADD_COUNT'; 

export const USER_STATUS = 'USER_STATUS'; 