export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';

export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const CART_ITEM_ADD = 'CART_ITEM_ADD';

export const CART_ITEM_REQUEST = 'CART_ITEM_REQUEST';

export const CART_ITEM_DELETE = 'CART_ITEM_DELETE';